In [384]:
pip install torch

Note: you may need to restart the kernel to use updated packages.


In [385]:
import torch
import torch.nn as nn

In [386]:
data = torch.Tensor([1,2,3])
softmax_function = nn.Softmax(dim=0)
output = softmax_function(data)
output

tensor([0.0900, 0.2447, 0.6652])

In [387]:
class MySoftmax(nn.Module):
    def __init__(self):
        super().__init__()
    
    def forward(self, x):
        x_exp = torch.exp(x)
        total = x_exp.sum(0,keepdims = True)
        return x_exp/total

my_softmax = MySoftmax()
output = my_softmax(data)
output

tensor([0.0900, 0.2447, 0.6652])

In [388]:
data = torch.Tensor([1,2,30000000])

In [389]:
output = softmax_function(data)
output

tensor([0., 0., 1.])

In [390]:
class StableSoftmax(nn.Module):
    def __init__(self):
        super().__init__()
    
    def forward(self, x):
        c = torch.max(x, dim = 0)
        x_exp = torch.exp(x-c.values)
        total = x_exp.sum(0,keepdims = True)
        return x_exp/total

In [391]:
stable_softmax = StableSoftmax()
output = stable_softmax(data)
output

tensor([0., 0., 1.])

In [392]:
torch.max(data, dim=0)

torch.return_types.max(
values=tensor(30000000.),
indices=tensor(2))

In [393]:
output = stable_softmax(torch.Tensor([1,2,3]))
output

tensor([0.0900, 0.2447, 0.6652])

In [394]:
# 2.
from abc import ABC, abstractmethod    
    
class Person(ABC):
    def __init__(self,name, yob):
        self.name = name 
        self.yob = yob

    @abstractmethod
    def describe(self):
        pass
    
    def get_yob(self):
        return self.yob
        
class Student(Person):
    def __init__(self, name, yob, grade):
        super().__init__(name, yob)
        self.__grade = grade
    
    def describe(self):
        print(f"Student: Name : {self.name} - YoB : {self.yob} - Grade : {self.__grade}")

class Doctor(Person):
    def __init__(self, name, yob, speciallist):
        super().__init__(name, yob)
        self.__speciallist = speciallist
    
    def describe(self):
        print(f"Doctor: Name : {self.name} - YoB : {self.yob} - Speciallist : {self.__speciallist}")

class Teacher(Person):
    def __init__(self, name, yob, subject):
        super().__init__(name, yob)
        self.__subject = subject
    
    def describe(self):
        print(f"Teacher: Name : {self.name} - YoB : {self.yob} - Subject : {self.__subject}")


In [395]:
student1 = Student("Thai", 1999,10)
student1.describe()

Student: Name : Thai - YoB : 1999 - Grade : 10


In [396]:
doctor1 = Doctor("Thai", 1991, "Anh")
doctor1.describe()

Doctor: Name : Thai - YoB : 1991 - Speciallist : Anh


In [397]:
teacher1 = Teacher("ABC", 1990,"Math")
teacher1.describe()

Teacher: Name : ABC - YoB : 1990 - Subject : Math


In [398]:
class Ward:
    def __init__(self, name):
        self.__name = name 
        self.__list_people = list()
    
    def add_person(self, person: Person):
        self.__list_people.append(person)
    
    def describe(self):
        print(f"Name : {self.__name}")
        for p in self.__list_people:
            p.describe()

In [399]:
ward1 = Ward("Ward1")

In [400]:
ward1.add_person(student1)

In [401]:
ward1.describe()

Name : Ward1
Student: Name : Thai - YoB : 1999 - Grade : 10


In [402]:
# 3
class Ward:
    def __init__(self, name):
        self.__name = name 
        self.__list_people = list()
    
    def add_person(self, person: Person):
        self.__list_people.append(person)
    
    def describe(self):
        print(f"Name : {self.__name}")
        for p in self.__list_people:
            p.describe()
            
    def count_doctor(self):
        counter = 0
        for p in self.__list_people:
            if isinstance(p, Doctor):
                counter +=1
            
        return counter
    
    def sort_yob(self):
        return self.__list_people.sort(key =lambda x: x.get_yob(), reverse = False)
    
    def compute_average(self):
        total = 0
        counter = 0
        for p in self.__list_people:
            if isinstance(p, Teacher):
                total += p.get_yob()
                counter += 1
        
        if counter == 0:
            return 0
            
        return total / counter

In [403]:
ward2 = Ward("Ward2")
ward2.add_person(student1)
ward2.add_person(doctor1)
ward2.add_person(teacher1)
ward2.count_doctor()

1

In [404]:
# d: sort according to Age 
ward2.sort_yob()
ward2.describe()

Name : Ward2
Teacher: Name : ABC - YoB : 1990 - Subject : Math
Doctor: Name : Thai - YoB : 1991 - Speciallist : Anh
Student: Name : Thai - YoB : 1999 - Grade : 10


In [405]:
# e 
ward2.compute_average()

1990.0

In [406]:
# Stack
class MyStack:
    def __init__(self, capacity):
        self.__capacity = capacity
        self.__stack = []
    
    def is_empty(self):
        return len(self.__stack) == 0
    
    def is_full(self):
        return len(self.__stack) == self.__capacity
    
    def push(self, item):
        if self.is_full():
            raise Exception('Overflow')
        self.__stack.append(item)
        
    def pop(self):
        if self.is_empty():
            raise Exception('Underflow')
        self.__stack.pop()
        
    def top(self):
        if self.is_empty():
            return "Stack is empty"
        return self.__stack[-1]

In [407]:
my_stack = MyStack(4)
my_stack.is_empty()
my_stack.push(5)
my_stack.is_empty()
my_stack.push(4)

In [408]:
my_stack.is_full()

False

In [409]:
my_stack.pop()

In [410]:
my_stack.is_empty()

False

In [411]:
my_stack.top()

5

In [412]:
# Queue
class MyQueue:
    def __init__(self, capacity):
        self.__capacity = capacity
        self.__queue = []
    
    def is_empty(self):
        return len(self.__queue) == 0
    
    def is_full(self):
        return len(self.__queue) == self.__capacity
    
    def enqueue(self, item):
        if self.is_full():
            raise Exception('Overflow')
        self.__queue.append(item)
        
    def dequeue(self):
        if self.is_empty():
            raise Exception('Underflow')
        self.__queue.pop(0)
        
    def front(self):
        if self.is_empty():
            print("Queue is empty")
            return
        return self.__queue[0]

In [413]:
my_queue = MyQueue(5)
my_queue.is_empty()

True

In [414]:
my_queue.enqueue(5)

In [415]:
my_queue.front()

5

In [416]:
my_queue.is_empty()

False

In [417]:
my_queue.enqueue(4)
my_queue.enqueue(3)
my_queue.enqueue(2)
my_queue.is_full()

False

In [418]:
my_queue.dequeue()

In [419]:
my_queue.dequeue()

In [420]:
my_queue.front()

3

In [421]:
data = torch . Tensor ([1 , 2 , 3])
softmax_function = nn . Softmax ( dim =0)
output = softmax_function ( data )
assert round ( output [0]. item () , 2) == 0.09
output

tensor([0.0900, 0.2447, 0.6652])

In [422]:
data = torch . Tensor ([5 , 2 , 4])
my_softmax = MySoftmax ()
output = my_softmax ( data )
assert round ( output [ -1]. item () , 2) == 0.26
output

tensor([0.7054, 0.0351, 0.2595])

In [423]:
data = torch . Tensor ([1 , 2 , 300000000])
my_softmax = MySoftmax ()
output = my_softmax ( data )
assert round ( output [0]. item () , 2) == 0.0
output

tensor([0., 0., nan])

In [424]:
data = torch . Tensor ([1 , 2 , 3])
softmax_stable = StableSoftmax()
output = softmax_stable ( data )
assert round ( output [ -1]. item () , 2) == 0.67
output

tensor([0.0900, 0.2447, 0.6652])